
export const DRINK_LIST_UPDATE = "DRINK_LIST_UPDATE"
export const REORDER_PRODUCT_UPDATE = "REORDER_PRODUCT_UPDATE"
export const CART_LIST_UPDATE = "CART_LIST_UPDATE"
export const CART_LIST_DELETE = "CART_LIST_DELETE"
export const CART_LIST_QTY_UPDATE = "CART_LIST_QTY_UPDATE"
export const LOGIN_SUCESS = "LOGIN_SUCESS"








